expect_damage: 100_000 #期望100w伤害，如果未达到期望伤害则在[last_check_time]时暂停
last_check_time: 2 #在剩余两秒的时候做最终结果检测检测
manual_last_check: True #如果设置为True则在[last_check_time]时暂停
operation_list:
    # 操作列表：不同操作属性之间用空格隔开
    # 时间 位置
    # 时间：秒数，可以带小数即毫秒。同一秒的UB顺序控制通过调整列表的顺序即可，
    # 也就是说操作列表的顺序必须是时间顺序
    # 位置：位置是根据近战到远程顺序1-5号位
    # 例如：1:00 中时 二号未需要释放UB
    # 60 2
    - 69 2
    - 64 3
    - 63 1
    - 63 4
    - 54 1
    - 53 2
    - 49 5