# expect_damage: 100_000 #期望100w伤害，如果未达到期望伤害则在[last_check_time]时暂停
# last_check_time: 2 #在剩余两秒的时候做最终结果检测检测
# manual_last_check: True #如果设置为True则在[last_check_time]时暂停
ub_check_threshold: 0.85 #sp条大于0.85确认为可释放UB状态
ub_check_timeout: 3 #如果UB未释放成功则在3秒内重复尝试
click_interval: 0.1 #每100毫秒尝试做一次点击操作 最好不要小于0.05
read_time_interval: 0.5 #每一秒读取一次战斗记录时间 最好不要小于0.5
operation_list:
    # 操作列表：不同操作属性之间用空格隔开
    # 时间 位置 偏移
    # 时间：秒数，可以带小数即毫秒。同一秒的UB顺序控制通过调整列表的顺序即可，
    # 也就是说操作列表的顺序必须是时间顺序
    # 位置：位置是根据近战到远程顺序1-5号位
    # 偏移：给小于1的小数，正常到指定时间就会释放UB，如果希望延后(押技能)可以设置这个值
    # 例如：1:00 中时 二号未需要释放UB
    # 60 2
    - 65 1
    - 62 3
    - 61 2
    - 59 4
    - 46 5
    - 44 1 0.6
    - 38 3
    - 29 4
    - 22 1
    - 19 5
    - 16 2
    - 14 3
    - 5 4
    - 3 1