# expect_damage: 100_000 #期望100w伤害，如果未达到期望伤害则在[last_check_time]时暂停
# last_check_time: 2 #在剩余两秒的时候做最终结果检测检测
# manual_last_check: True #如果设置为True则在[last_check_time]时暂停
gpu: True # 是否开启GPU加速
ub_check_threshold: 0.85 #sp条大于0.85确认为可释放UB状态
ub_check_timeout: 5 #如果UB未释放成功则在5秒内重复尝试
click_interval: 0.1 #每200毫秒尝试做一次点击操作 最好不要小于0.1
read_time_interval: 0.1 #每0.5秒读取一次战斗记录时间 最好不要小于0.5
job_list:
    # 操作列表：不同操作属性之间用空格隔开
    # 时间 位置 偏移
    # 时间：秒数，可以带小数即毫秒。同一秒的UB顺序控制通过调整列表的顺序即可，
    # 也就是说操作列表的顺序必须是时间顺序
    # 位置：位置是根据近战到远程顺序1-5号位
    # 偏移：给小于1的小数，正常到指定时间就会释放UB，如果希望延后(押技能)可以设置这个值
    # 例如：1:00 中时 二号位需要释放UB
    # 60 2
    "C2狼姬克黄栞":
        - 77 5
        - 72 1 0.6
        - 72 2 0.8
        - 71 4 0.6
        - 69 5 0.6
        - 67 3 0.8
        - 63 1 0.6
        - 62 2
        - 59 5
        - 53 5
        - 52 3 0.8
        - 51 1
        - 47 2
        - 43 5
        - 40 4 0.8
        - 37 1 0.8
        - 36 2
        - 36 5
        - 35 3 1.2
        - 27 1
        - 27 2
        - 26 5
        - 20 3
        - 20 5
        - 15 1 0.8
        - 15 2 1
        - 13 4
        - 9 5 0.6
        - 4 1 0.8
        - 3 3 0.2
        - 1 2
        - 1 5
    "c3黑骑狼狗病吉他(ok)":
        - 67 3
        - 67 5 1
        - 65 2 0.4
        - 61 4 0.8
        - 60 1
        - 58 5
        - 52 2 0.2
        - 50 3 0.2
        - 43 4 0.9
        - 43 5 1
        - 32 1
        - 32 2
        - 27 3 0.1
        - 27 5 0.15
        - 25 4 0.6
        - 19 2 0.6
        - 14 5 0.6
        - 5 1
        - 3 3
        - 1 5
        - 1 4
        - 1 2
