listen_mouse_event: False # 设置为True时在鼠标点击后打印日志，押技能找适合的延后时间时使用，先手动点，然后看日志输出的延迟时间信息
use_ocr: False # 是否使用ocr识别时间
gpu: True # 是否开启GPU加速， 只有在使用ocr时才有效果
ub_check_threshold: 0.85 #sp条大于0.85确认为可释放UB状态
ub_check_timeout: 3 #如果UB未释放成功则在5秒内重复尝试
click_interval: 0.1 #每200毫秒尝试做一次点击操作 最好不要小于0.1
read_time_interval: 0.1 #每0.5秒读取一次战斗记录时间 最好不要小于0.5
job_list:
    # 操作列表：不同操作属性之间用空格隔开
    # 时间 位置 偏移
    # 时间：秒数，可以带小数即毫秒。同一秒的UB顺序控制通过调整列表的顺序即可，
    # 也就是说操作列表的顺序必须是时间顺序
    # 位置：位置是根据近战到远程顺序1-5号位
    # 偏移：给小于1的小数，正常到指定时间就会释放UB，如果希望延后(押技能)可以设置这个值
    # 例如：1:00 中时 二号位需要释放UB
    # 60 2
    "Do Nothing":
        - -1 -1
    "C3 黄骑栞":
        - 79 5
        - 76 4
        - 75 1
        - 74 5
        - 69 1 0.2
        - 69 2 0.8
        - 67 5
        - 61 1
        - 60 2 0.2
        - 56 5 0.5
        - 55 1 0.7
        - 54 4 5
        - 52 1
        - 52 5 0.8
        - 51 2 0.2
        - 43 1
        - 42 5
        - 42 2 0.5
        - 41 3
        - 38 1
        - 34 4
        - 33 5
        - 33 2 0.2
        - 30 1
        - 27 5
        - 26 1
        - 23 2
        - 21 1 0.3
        - 21 3 0.8
        - 20 5
        - 17 4
        - 16 2
        - 14 1 0.1
        - 10 2
        - 9 1
        - 9 5 0.5
        - 3 1
        - 2 2
        - 1 5
        - 1 2

