# expect_damage: 100_000 #期望100w伤害，如果未达到期望伤害则在[last_check_time]时暂停
# last_check_time: 2 #在剩余两秒的时候做最终结果检测检测
# manual_last_check: True #如果设置为True则在[last_check_time]时暂停
ub_check_threshold: 0.85 #sp条大于0.85确认为可释放UB状态
ub_check_timeout: 5 #如果UB未释放成功则在3秒内重复尝试
click_interval: 0.05 #每100毫秒尝试做一次点击操作 最好不要小于0.05
read_time_interval: 0.3 #每0.5秒读取一次战斗记录时间 最好不要小于0.5
job_list:
    # 操作列表：不同操作属性之间用空格隔开
    # 时间 位置 偏移
    # 时间：秒数，可以带小数即毫秒。同一秒的UB顺序控制通过调整列表的顺序即可，
    # 也就是说操作列表的顺序必须是时间顺序
    # 位置：位置是根据近战到远程顺序1-5号位
    # 偏移：给小于1的小数，正常到指定时间就会释放UB，如果希望延后(押技能)可以设置这个值
    # 例如：1:00 中时 二号未需要释放UB
    # 60 2
    "A3剑克换yls栞":
        - 76 5
        - 73 4
        - 64 5
        - 63 1
        - 62 2
        - 60 4
        - 54 3
        - 48 4
        - 47 5
        - 37 4
        - 35 2
        - 35 1
        - 32 5
        - 28 3
        - 22 4
        - 19 5
        - 14 4
        - 1 2
        - 1 1
        - 1 3
        - 1 4
        - 1 5
    "A4狗511狼病忍":
        - 64 1 0.2
        - 60 3
        - 60 4
        - 60 2
        - 59 5
        - 35 3
        - 32 5
        - 24 4
        - 18 2
        - 9 3
        - 3 5
        - 1 4
    "A5狗狼锤病克":
        - 60 2
        - 60 4
        - 60 1
        - 59 5
        - 52 3
        - 42 1
        - 36 2
        - 36 4
        - 32 5
        - 28 3
        - 19 1
        - 10 2
        - 2 4
        - 1 5
        - 1 1
        - 1 3