# expect_damage: 100_000 #期望100w伤害，如果未达到期望伤害则在[last_check_time]时暂停
# last_check_time: 2 #在剩余两秒的时候做最终结果检测检测
# manual_last_check: True #如果设置为True则在[last_check_time]时暂停
ub_check_threshold: 0.85 #sp条大于0.85确认为可释放UB状态
ub_check_timeout: 5 #如果UB未释放成功则在5秒内重复尝试
click_interval: 0.2 #每200毫秒尝试做一次点击操作 最好不要小于0.1
read_time_interval: 0.5 #每0.5秒读取一次战斗记录时间 最好不要小于0.5
job_list:
    # 操作列表：不同操作属性之间用空格隔开
    # 时间 位置 偏移
    # 时间：秒数，可以带小数即毫秒。同一秒的UB顺序控制通过调整列表的顺序即可，
    # 也就是说操作列表的顺序必须是时间顺序
    # 位置：位置是根据近战到远程顺序1-5号位
    # 偏移：给小于1的小数，正常到指定时间就会释放UB，如果希望延后(押技能)可以设置这个值
    # 例如：1:00 中时 二号位需要释放UB
    # 60 2
    "空":
        - -1 1
    "B4狗狼智克普白":
        - 67 3
        - 64 1
        - 62 2
        - 53 4
        - 49 3
        - 46 5
        - 45 1
        - 38 2
        - 30 3
        - 30 4
        - 24 1
        - 18 5
        - 13 2
        - 12 3
        - 5 4
        - 1 1
    "B5狼病511忍情":
        - 60 2
        - 60 1
        - 60 4
        - 59 3
        - 59 5
        - 45 2
        - 43 3
        - 43 4
        - 39 5
        - 33 2
        - 32 4
        - 25 3
        - 25 1
        - 21 5
        - 14 2
        - 12 4
        - 6 5
        - 3 4
        - 2 2
        - 1 3