# 这个是用于清日常的配置文件
Accounts: #存账号信息
  -
    account: 'YourAccount'
    password: 'YourPassword'
Extra:
  dnpath: 'N:\dnplayer2' # 雷电模拟器的安装目录
  ocr: False
Task: #配置执行任务,配置任务名称，如果需要传入参数在下面增加参数，可以根据不同的账号序号配置任务。
      #账号会执行小于等于并且离它最近的序号的任务列表
  1: #配置账号大于等于1的进行以下操作
     #最好每个任务结束后设置tohomepage，因为每个任务都是按照当前在首页的情况执行的
    -
      - guild_like # 点赞行会成员
    # 下面注释部分用于有免费10连的时候用
    # 这里没判断是否是免费的十连，所以第二个参数最好不要传True
    # 如果当前没有免费的十连的话就直接把钻石花光了
    # - 
    #   - tohomepage
    # -
    #   - choushilian #抽取免费十连
    #   - False #是否抽取所有免费十连
    -
      - tohomepage
    -
      - normal_gacha #普通扭蛋10连
    -
      - tohomepage
    -
      - get_quest_reward
    -
      - get_power #去公会之家领体力
    -
      - arena #打一把竞技场
    -
      - tohomepage
    -
      - princess_arena #打一把公主竞技场
    -
      - tohomepage
    -
      - explore #探索
    -
      - tohomepage
    -
      - research #圣迹调查
    -
      - tohomepage
    -
      - shop_buy #商店购买
      -
        1: # 第一个tab（通常）购买前四个
          - 1
          - 2
          - 3
          - 4
        2: # 第二个tab（地下城）里购买第一个
          - 1
        3: # 第三个tab（竞技场）里购买第一个和第四个
          - 1
          - 4
        4: # 第四个tab （公主竞技场）购买第一个
          - 1
    -
      - tohomepage
    -
      - dungeon_saodang  #扫荡地下城
      - 5 # 极限难度地下城
      - 1  #使用编号1队过小怪
      - '4' # 选择编组4过boss
      - '1,2,3,4,5,6,7,8,9,10' #使用上面选择的编组中编号1到10队过boss，小队之间用','分割
      - False # 结束后是否退出地下城，在无法完成地下城时使用
    -
      - tohomepage
    - 
      - saodang_hard  #过超难图
      - 3 # 开始关卡
      - 1  # 结束关卡
      - 2  # VERY HARD
    # 下面部分用于活动期间清体力
    # -
    #   - tohomepage
    # -
    #   - activity_saodang  # 清活动图的日常，由于每次活动不一样，该任务每次活动更新一次做支持
    #   - True # 是否刷活动困难章节和高难boss
    #   - True # 是否将剩余体力花费在活动普通章节上
    -
      - tohomepage
    - 
      - saodang_hard  #过困难章节把体力用光，这里判断没体力后会自行终止
      - 60 # 开始关卡 60对应 20-3
      - 1  # 结束关卡
    -
      - tohomepage
    -
      - get_quest_reward
    -
      - tohomepage
    -
      - get_gift
    
    

    