# 这个是用于清日常的配置文件
Accounts: #存账号信息
  -
    account: 'YourAccount'
    password: 'YourPassword'
Extra:
  dnpath: 'N:\dnplayer2' # 雷电模拟器的安装目录
  ocr: False
Task: #配置执行任务,配置任务名称，如果需要传入参数在下面增加参数，可以根据不同的账号序号配置任务。
      #账号会执行小于等于并且离它最近的序号的任务列表
  1: #配置账号大于等于1的进行以下操作
     #最好每个任务结束后设置tohomepage，因为每个任务都是按照当前在首页的情况执行的
    # -
    #   - landsol_cup # 兰德索尔杯 随机选一个角色
    -
      - guild_like # 点赞行会成员
    # 这里没判断是否是免费的十连，所以第二个参数最好不要传True
    # 如果当前没有免费的十连的话就直接把钻石花光了
    # - 
    #   - tohomepage
    # -
    #   - choushilian #抽取免费十连
    #   - False #是否抽取所有免费十连
    -
      - tohomepage
    -
      - normal_gacha #普通扭蛋10连
    -
      - tohomepage
    -
      - get_quest_reward
    -
      - get_power #去公会之家领体力
    -
      - arena #打一把竞技场
    -
      - tohomepage
    -
      - princess_arena #打一把公主竞技场
    -
      - tohomepage
    -
      - explore #探索
    -
      - tohomepage
    -
      - research #圣迹调查
    -
      - tohomepage
    -
      - dungeon_saodang  #扫荡地下城
      - 6 # 绿龙
      - 1  #使用编号1队过小怪
      - '4' # 选择编组4过boss
      - '1,2,3,4,5,6,7,8,9,10' #使用上面选择的编组中编号1到10队过boss，小队之间用','分割使用''空串代表不打boss
      - False # 结束后是否退出地下城，在无法完成地下城时使用
    -
      - tohomepage
    -
      - quick_saodang # 使用快捷扫荡功能（游戏内置功能）
      - 2 # 使用预设2
    -
      - tohomepage
    -
      - activity_saodang  # 清活动图的日常，由于每次活动不一样，该任务每次活动更新一次做支持
      - True # 是否刷活动困难章节和高难boss
      - False # 是否将剩余体力花费在活动普通章节上
    # 扫荡露娜塔
    # -
    #   - tohomepage
    # -
    #   - luna_tower_saodang
    -
      - tohomepage
    -
      - shop_buy #商店购买
      -
        1: # 第一个tab（通常）购买前四个
          - 1
          - 2
          - 3
          - 4
        2: # 地下城
          - 1
        2_config: # 第二个栏的额外配置
          time: 3 # 执行3次，相当于重置2次
          buy_equip: True # 购买装备
          first_equip: 12 # 第一个装备位置
          end_equip: 19 # 最有一个装备的位置
          buy_threshold: 300 # 购买所有小于300的装备
          total_item_count: 20 # 当前tab下购买物品数量上限，用来计算是否是最后一行
        5: # 行会
          - 5
        8: # 限时，放到扫荡之后确保之前已经触发出来限时了
          - 1
          - 2
    -
      - tohomepage
    -
      - get_quest_reward  # 最后领下任务
    -
      - tohomepage
    -
      - get_gift # 领下礼物
    
    

    